### ISSUE TITLE
Dataset creation problem

### ISSUE THREAD

**Issue by Varshithpolu** [chrisdonahue/wavegan#4]
I have been trying to create the dataset in the format required for training using the command you have provided i have wav files and i changed the command of ext to wave but still the tfrecord files created seems to be empty and when i train tensorflow says we are trying to run infinitly on an empty dataset

**Comment by chrisdonahue** [comment]
Change ext to 'wav' not 'wave'

I need more information if that doesn't fix it

**Comment by Varshithpolu** [comment]
I have used "wav" in the command but still the problem persists 
i have attaches the screenshots below 
![screenshot from 2018-06-04 01 02 07](https://user-images.githubusercontent.com/25304603/40890403-0eb312ec-6793-11e8-881c-2caded1c954e.png)

this is the command i used 
![screenshot from 2018-06-04 01 02 22](https://user-images.githubusercontent.com/25304603/40890407-26162640-6793-11e8-986f-06085716343a.png)

Thanks in advance

**Comment by Varshithpolu** [comment]
Hi,
sorry to bother you again,
but that didn't fix my problem
I would attach a wav file from my data .
 could you please check with them .
[test.zip](https://github.com/chrisdonahue/wavegan/files/2074658/test.zip)
Thanks in advance

**Comment by chrisdonahue** [comment]
I was able to successfully make tfrecords from those two files using my script. Not sure what the issue is.

What version of tensorflow are you using? Could you print out `npershard` in the script to see if that's the issue? Also, can you print `_slices.shape` after line 114? This information might help me debug the issue.

I suspect it might be an issue with FFmpeg

**Comment by kennu** [comment]
Hello. Just a note to @Varshithpolu, I had the same problem with "empty dataset" errors. I solved it by using a longer wav file (several minutes instead of 10 seconds pieces).

**Comment by LiangqunLu** [comment]
I have the same issue, in which the *tfrecord is empty. I downloaded the code 2 days ago. After I tested line by line, I figured out the issue from FFmpeg '_UnavailableError: FFmpeg must be installed to run this op. FFmpeg can be found at http://www.ffmpeg.org.
	 [[Node: DecodeAudioV2 = DecodeAudioV2[stream="", _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReadFile, DecodeAudioV2/file_format, DecodeAudioV2/samples_per_second, DecodeAudioV2/channel_count)]]_'

In my Ubuntu system, the issue was gone after I installed ffmpeg. However, another issue shows up 'example = tf.train.Example(features=tf.train.Features(feature={
          #'id': tf.train.Feature(bytes_list=tf.train.BytesList(value=audio_id)),
          'label': tf.train.Feature(bytes_list=tf.train.BytesList(value=audio_label)),
          'slice': tf.train.Feature(int64_list=tf.train.Int64List(value=[j])),
          'samples': tf.train.Feature(float_list=tf.train.FloatList(value=_slice))
        }))'
# the line I commented 
The error information is 'File "<ipython-input-23-145a0af1c256>", line 1, in <module>
    tf.train.Feature(bytes_list=tf.train.BytesList(value=audio_id))

TypeError: 'S' has type str, but expected one of: bytes'

But anyway, the array is generated from ' tf.train.Feature(float_list=tf.train.FloatList(value=_slice))'  and the tfrecord file is not empty now.

**Comment by chrisdonahue** [comment]
@LiangqunLu I think that issue arises from using Python 3 which differentiates between `str` and `bytes`. You can always delete [this line](https://github.com/chrisdonahue/wavegan/blob/master/data/make_tfrecord.py#L122) to avoid this issue. The labels are only added to the records for conditional GAN experiments

**Comment by anooptoffy** [comment]
I had issue with the tf_records creation, but When I used the following command all the issue earlier report were faced by me too, it got fixed.

python data/make_tfrecord.py \
        ./new_data/sc09/train \
        ./new_data/train \
        **--name train \**
        --ext wav \
        --fs 16000 \
        --nshards 128 \
        --slice_len 1.5 \

I think --name train attribute was missing from everyone of us.

**Comment by chrisdonahue** [comment]
If anyone is having trouble with making datasets (empty TFrecord files), make sure FFmpeg is installed. It is required by the `make_tfrecords.py` file. On ubuntu 16: `sudo apt install ffmpeg`

**Comment by wbwdhr** [comment]
@Varshithpolu What method did you use to solve this problem?  I also encountered this problem when I tried to build Dataset for SC09. Please help me！
I've already installed ffmpeg. But it still didn't work .
My tensorflow-gpu version is 1.4

this is the command i used：
python data/make_tfrecord.py ./sc09/train ./train --ext wav --fs 16000 --nshards 128 --slice_len 1.5

**Comment by chrisdonahue** [comment]
You shouldn't have to build the dataset for SC09 from WAV files. You can get it prebuilt here:

https://drive.google.com/open?id=1qRdAWmjfWwfWIu-Qk7u9KQKGINC52ZwB
