### ISSUE TITLE
Generate 8 seconds' sample

### ISSUE THREAD

**Issue by colonder** [chrisdonahue/wavegan#42]
Hi Chris,
I'd like to generate 8 seconds' samples with your model. Would you be so kind as to give any hint on how to modify the model?

**Comment by chrisdonahue** [comment]
Sure, you should be able to modify the WaveGAN generator to support 8 second samples by increasing the starting `dim_mul` variable:

https://github.com/chrisdonahue/wavegan/blob/master/wavegan.py#L43

Alternatively you can just halve whatever sample rate you're working with using `--data_sample_rate` to go from 4 to 8 second clips.

**Comment by jwb95** [comment]
Hi,
I have a modell which I trained with a `SLICE_LEN` of only `16384` for test purposes.
So this modell is capable of generating ~1 second at a sample rate of 16000.

I increased the `dim_mul` from 16 to `32, 64, 128, 256...` without noticing a difference in the length.
Halving the sample rate obviously worked to go from ~1 sec up to ~2 sec clips.

Could you give me clearer insight on how to set the `dim_mul` to achieve longer audio? Since I'm not quite sure what this parameter actually manipulates I'm also wondering how this will affect the quality of the generated audio.

Thanks

**Comment by chrisdonahue** [comment]
Sorry for the late reply. `dim_mul` will not change the length of the audio. However, for longer slices (as specified by the `data_slice_len` parameter), you will likely need to reduce the value of `dim_mul` or `train_batch_size` to ensure that the model still fits into memory.

**Comment by jvel07** [comment]
Hi, so under this context, what's the difference between data_sample_rate and data_slice_len?

**Comment by jwb95** [comment]
data_sample_rate describes the amount of samples used to represent 1 second of audio. cd-standard is 44100 for example. data_slice_len refers to the reception size of the model. e.g. with a data_slice_len of 44100 and s data_sample_rate of 44100 you could let the model learn to generate one second of 44100hz audio.
