### ISSUE TITLE
train_wavegan.py freezes at line 202

### ISSUE THREAD

**Issue by wenting-zhao** [chrisdonahue/wavegan#55]
When I ran ``python train_wavegan.py train ./train_tmp --data_dir ./data/sc09/train/``, it freezes at line 202, and ctrl-c won't kill it.  Any ideas what might be happening here?  Our conjecture is that there might be some issues with data loader, and were wondering if anybody else ran into this and may have a fix?  Thanks!

Both tested on linux ubuntu and centOS, with python 3.5 and 3.6.  Tested GPUs are Tesla V100 and P4000.  All required packages are the same as written in README.  All of the configs above freeze at the same point.

**Comment by chrisdonahue** [comment]
Yeah likely an issue with the data loader. I haven't run into this before. Are you sure the `--data_dir` path is right? What does the code say for `print('Found {} audio files in specified directory'.format(len(fps)))`? Did you try `--data_fast_wav`?

**Comment by chrisdonahue** [comment]
I figured it out. It was a documentation error, sorry about that! I've updated the README

Try changing the command to:
`python train_wavegan.py train ./train_tmp --data_dir ./data/sc09/train/ --data_first_slice --data_pad_end --data_fast_wav`

`--data_first_slice` ensures that only the leftmost slice from each audio file is used; `--data_pad_end` ensures that audio waveforms are padded to fill the training slice length; `--data_fast_wav` uses scipy instead of librosa to decode WAV files more quickly.

Feel free to reopen if that doesn't fix things.
